### ISSUE TITLE
Async Main

### ISSUE THREAD

**Issue by marinasundstrom** [thanhle0212/FindPrimeNumbers#1]
Actually, since one of the latest versions you can write async code in Main.

```csharp
public static async Task Main(string[] args)
```

Make sure you are targeting the latest C# language version.

**Comment by thanhle0212** [comment]
Ahh, thank you, bro! You're correct.

Since C# 7.1, we could use Async in Main - I've just double-checked. Let me update the source code accordingly. 

Thank you again!
